### ISSUE TITLE
Publishing does not work

### ISSUE THREAD

**Issue by ttusar** [numbbo/temp-doc#1]
Running `quarto publish` on a Windows machine fails (while `quarto preview` works without problem):

```console
(numbbo-coco) PS D:\Delo\Github\numbbo-temp-doc> quarto publish
? Update site at https://numbbo.github.io/temp-doc/? (Y/n) » Yes
From https://github.com/numbbo/temp-doc
 * branch            gh-pages   -> FETCH_HEAD
Rendering for publish:

[1/5] def.qmd
[2/5] ecdfs.qmd
[3/5] index.qmd
[4/5] ppdata.qmd
[5/5] vis.qmd

fatal: 'gh-pages' is already checked out at 'D:/Delo/Github/numbbo-temp-doc'
ERROR: Error executing 'git': The directory name is invalid. (os error 267)

Error: Error executing 'git': The directory name is invalid. (os error 267)
    at execProcess (file:///C:/Program%20Files/Quarto/bin/quarto.js:5630:15)
    at withWorktree (file:///C:/Program%20Files/Quarto/bin/quarto.js:120629:11)
    at async Object.publish4 [as publish] (file:///C:/Program%20Files/Quarto/bin/quarto.js:120468:5)
    at async publishSite (file:///C:/Program%20Files/Quarto/bin/quarto.js:121230:38)
    at async publish5 (file:///C:/Program%20Files/Quarto/bin/quarto.js:121448:61)
    at async doPublish (file:///C:/Program%20Files/Quarto/bin/quarto.js:121404:13)
    at async publishAction (file:///C:/Program%20Files/Quarto/bin/quarto.js:121415:9)
    at async Command.fn (file:///C:/Program%20Files/Quarto/bin/quarto.js:121392:9)
    at async Command.execute (file:///C:/Program%20Files/Quarto/bin/quarto.js:8437:13)
    at async quarto (file:///C:/Program%20Files/Quarto/bin/quarto.js:127545:5)
(numbbo-coco) PS D:\Delo\Github\numbbo-temp-doc> quarto publish

```

**Comment by ttusar** [comment]
Not sure whether this is connected, but Github Actions fail now too: https://github.com/numbbo/temp-doc/actions/runs/7142043427/job/19450483958

They seem to want to use Jekyll although there is a `.nojekyll` file in the repository now - as per instructions from https://quarto.org/docs/publishing/github-pages.html#render-to-docs

**Comment by ttusar** [comment]
Olaf fixed it :-)
